# Generated by Django 5.0 on 2023-12-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microorganisms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bacteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microorganisms', to='MyApp.bacteria')),
                ('fungi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microorganisms', to='MyApp.fungi')),
            ],
        ),
    ]
