# Generated by Django 5.0 on 2023-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_bacteria_properties_alter_fungi_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microorganisms',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
